source 'https://github.com/CocoaPods/Specs.git'

target 'ImpressionKitExample' do
  use_frameworks!
  platform :ios, '12.0'

  pod 'ImpressionKit', :path=>'../'
  pod 'GDPerformanceView-Swift', '~> 2.0.3'
  pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.7'
  pod 'Eureka'

end

target 'MacOSExample' do
  use_frameworks!
  platform :osx, '11.0'
  
  pod 'ImpressionKit', :path=>'../'
  
end

#post_install do |installer|
#    installer.generated_projects.each do |project|
#        project.targets.each do |target|
#            target.build_configurations.each do |config|
#                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#            end
#        end
#    end
#end
