source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'ImpressionKitExample' do
  use_frameworks!

  pod 'ImpressionKit', :path=>'../'
  pod 'GDPerformanceView-Swift', '~> 2.0.3'
  pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.7'
  pod 'Eureka'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end
