inhibit_all_warnings!
platform :ios, '8.0'

target 'SHPExposureDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SHPExposure', :path=>'../'
  pod 'GDPerformanceView', '~> 1.3.1'
  pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.7'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
