platform :ios, '13.0'
inhibit_all_warnings!

target 'SHPExposureDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'SHPExposure', :path=>'../'
  pod 'GDPerformanceView-Swift', '~> 2.0.3'
  pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.7'
  pod 'Eureka', '~> 5.2.1'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
